using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using NUnit.Framework;

namespace GeneratedNamespace.Tests
{

	[TestFixture]
	public class ModelTest
	{
		[Test]
		public void UpdateNamespaceTest()
		{
			Assert.Fail("autogeneratedtest");
		}

	}
}