using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using NUnit.Framework;

namespace GeneratedNamespace.Tests
{

	[TestFixture]
	public class OpenAssemblyDialogTest
	{
		[Test]
		public void OpenFileDialogTest()
		{
			Assert.Fail("autogeneratedtest");
		}

		[Test]
		public void ShowMessageTest()
		{
			Assert.Fail("autogeneratedtest");
		}

	}
}