using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using NUnit.Framework;

namespace GeneratedNamespace.Tests
{

	[TestFixture]
	public class RelayCommandTest
	{
		[Test]
		public void CanExecuteTest()
		{
			Assert.Fail("autogeneratedtest");
		}

		[Test]
		public void ExecuteTest()
		{
			Assert.Fail("autogeneratedtest");
		}

	}
}